import { CMCoor } from './CMCoor';
import { CMLayout } from './CMLayout';
import { CMStyle } from './CMStyle';
import { CMCopy } from './CMCopy';
import { CMEMeta } from './CMEMeta';
import { CMTBObject } from './CMTBObject';
import { CMTBMarking } from './CMTBMarking';
import { CMTBQuizedit } from './CMTBQuizedit';
import { CMTBFont } from './CMTBFont';
import { CMTBLine } from './CMTBLine';

export class CMSettings {
  public id: number;
  public maxid: number;
  public mode: string;
  public seltb: string;
  public coor: CMCoor;
  public pointArray: CMCoor[];
  public style: CMStyle;
  public debug: boolean;
  public cngtemp: boolean;
  public dragging: boolean;
  public copy: CMCopy;
  public copycolor: string;
  public latexcolor: string;
  public mnemocolor: string;
  public contentPos: number;
  public minimapupdate: number;
  public zoom: number;
  public deletedcme: number[];
  public currentMeta: CMEMeta;
  public epath: string;
  public cmap: CMLayout;
  public tblayout0: CMLayout;
  public tblayout1: CMLayout;
  public wlayout0: CMLayout;
  public widget0: string;
  public wlayout1: CMLayout;
  public widget1: string;
  public menue: CMLayout;
  public cmtbobject: CMTBObject;
  public cmtbmarking: CMTBMarking;
  public cmtbquizedit: CMTBQuizedit;
  public cmtbfont: CMTBFont;
  public cmtbline: CMTBLine;
}
